name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 @${{github.actor}}! Thank you for opening your first issue on on fastai.  We are so happy that you have decided to contribute and value your contribution. Please read these materials before proceeding: [Contributing Guide](https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/fastai/fastai/blob/master/CODE_OF_CONDUCT.md)."
        pr-message: "👋 @${{github.actor}}! Thank you for opening your first pull request on on fastai. We are so happy that you have decided to contribute and value your contribution. Please read these materials before proceeding: [Contributing Guide](https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/fastai/fastai/blob/master/CODE_OF_CONDUCT.md)."
 
